# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_auto_20180603_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='barslocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
