# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_barslocation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='barslocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
