# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_barslocation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='barslocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='barslocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
