# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0006_auto_20180603_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='barslocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
