# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-05 01:50
from __future__ import unicode_literals

import bars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0007_barslocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barslocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[bars.validators.validate_category]),
        ),
    ]
